apiVersion: apps/v1
kind: Deployment
metadata:
  name: kbot
  labels:
    app: kbot
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: kbot
  template:
    metadata:
      labels:
        app: kbot
    spec:
      containers:
      - name: kbot
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
