# values.yaml - центральне місце для всіх змінних
image:
  repository: andreysvirid/kbot2
  tag: "v1.0.0-f34e424" #tag: "v1.0.0-610715b"

service:
  type: ClusterIP   # додаємо тип сервісу
  port: 80

serviceAccount:
  create: false

env:
  - name: TELEGRAM_TOKEN
    valueFrom:
      secretKeyRef:
        name: telegram-token
        key: token
