apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  path: ./flux      # <-- шлях у репо, де знаходяться YAML ! # тут лежить helmrelease.yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
#  validation: client