apiVersion: apps/v1
kind: Deployment
metadata:
  name: kbot
  labels:
    app: kbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kbot
  template:
    metadata:
      labels:
        app: kbot
    spec:
      containers:
        - name: kbot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 80
          env:
            {{- if .Values.env }}
            {{- toYaml .Values.env | nindent 12 }}
            {{- end }}
