apiVersion: apps/v1
kind: Deployment
metadata:
  name: kbot
  labels:
    app: kbot
spec:
  replicas: 1                       # кількість Podів
  selector:
    matchLabels:
      app: kbot                     # Deployment знаходить Podи по лейблу
  template:
    metadata:
      labels:
        app: kbot
    spec:
      containers:
        - name: kbot
          # Беремо образ із values.yaml
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          # Пробіг по env змінних з values.yaml
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              {{- if .value }}
              value: {{ .value }}
              {{- end }}
              {{- if .valueFrom.secretKeyRef }}
              valueFrom:
                secretKeyRef:
                  name: {{ .valueFrom.secretKeyRef.name }}
                  key: {{ .valueFrom.secretKeyRef.key }}
              {{- end }}
            {{- end }}