apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: kbot-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/andreysvirid/gke-flux-infra
  ref:
    branch: develop