apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kbot
  namespace: demo-helm
spec:
  interval: 1m
  chart:
    spec:
      chart: kbot
      sourceRef:
        kind: GitRepository
        name: kbot-repo
        namespace: flux-system
      version: "*"
  values:
    image:
      repository: andreysvirid/kbot2
      tag: "v1.0.4"
    service:
      type: ClusterIP
      port: 80
    serviceAccount:
      create: false
    ingress:
      enabled: false
    autoscaling:
      enabled: false
    env:
      - name: TELEGRAM_TOKEN
        valueFrom:
          secretKeyRef:
            name: telegram-token
            key: token 
       