apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gke-flux-infra
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/gke-flux-infra
      sourceRef:
        kind: GitRepository
        name: gke-flux-infra   # Назва GitRepository, який Flux відслідковує
  values:
    replicaCount: 2
    image:
      repository: andreysvirid/gke-flux-infra #your dockerhub username
      tag: latest
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 80
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
