apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kbot
  namespace: demo-helm
spec:
  chart:
    spec:
      chart: .
      sourceRef:
        kind: GitRepository
        name: flux-system
        interval: 1m
  interval: 1m
  values:
    telegramToken: "TEST"   # поки без секрету