apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bot-project2
  namespace: demo-helm
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    image:
      repository: andreysvirid/kbot2
      tag: "v1.0.0-4ce328a"
    telegram:
      token:
        valueFrom:
          secretKeyRef:
            name: telegram-token
            key: token          #kubectl create secret generic telegram-token \ --from-literal=token=7957704809:AAHq3Supo-FS4o1q8pqydBvdXY4GGwO3zeQ \-n demo-helm