apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kbot
  namespace: demo-helm
spec:
  interval: 1m
  chart:
    spec:
      chart: kbot                  # назва чарту всередині папки charts
      sourceRef:
        kind: GitRepository
        name: kbot-repo
        namespace: flux-system
      version: '*'                 # можна конкретний тег чарту або '*'
  values:
    image:
      repository: andreysvirid/kbot2
      tag: v1.0.4
    service:
      port: 80