apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kbot
  namespace: demo-helm
spec:
  interval: 1m
  chart:
    spec:
      chart:  ./charts/kbot  # або ім’я чарта, якщо з HelmRepository
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    image:
      repository: andreysvirid/kbot2
      tag: v1.0.0-c937981
    service:
      port: 80