apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  path: ./flux        # Вказуємо відносний шлях до папки flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: demo-helm