apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kbot.fullname" . }}
  labels:
    {{- include "kbot.labels" . | nindent 4 }}
{{- if .Values.serviceAccount.create }}
automountServiceAccountToken: true
{{- end }}
