name: Build & Deploy kbot

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: andreysvirid/kbot #your-dockerhub-username/kbot
      CHART_PATH: ./charts/kbot
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} #docker username
          password: ${{ secrets.DOCKER_PASSWORD }} #docker password
      - run: docker build -t $IMAGE_NAME:latest .
      - run: docker push $IMAGE_NAME:latest
      - run: |
          yq eval ".image.tag = \"latest\"" -i $CHART_PATH/values.yaml
          git config --global user.email "flux-bot@example.com"
          git config --global user.name "flux-bot"
          git add $CHART_PATH/values.yaml
          git commit -m "Update Docker image tag to latest [skip ci]" || echo "No changes to commit"
          git push origin main
