name: CI/CD

on:
  push:
    branches: [ develop ]

env:
  TARGETARCH: amd64
  TARGETOS: linux
  IMAGE_REGISTRY: docker.io
  IMAGE_REPOSITORY: andreysvirid/kbot

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout main
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2️⃣ Run tests
      - name: Run tests
        run: |
          go mod tidy
          go test ./...

      # 3️⃣ Login to Docker Hub
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4️⃣ Build & push Docker image
      - name: Build & Push
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          IMAGE_TAG="v1.0.0-${SHORT_SHA}-${TARGETOS}-${TARGETARCH}"
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          docker buildx build \
            --platform ${{ env.TARGETOS }}/$TARGETARCH \
                 -t ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:${IMAGE_TAG} \
            --push \
            .
           
  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout main
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2️⃣ Update Helm chart
      - name: Update Helm chart
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          VERSION="v1.0.0-${SHORT_SHA}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          yq -i '.image.repository = strenv(IMAGE_REPOSITORY) | .image.tag = strenv(VERSION)' helm/values.yaml

      # 8️⃣ Update helm/values.yaml
      - name: Update helm/values.yaml
        run: |
          yq e -i ".image.tag = \"${IMAGE_TAG}\"" helm/values.yaml
          yq e -i ".image.os = \"${OS}\"" helm/values.yaml
          yq e -i ".image.arch = \"${ARCH}\"" helm/values.yaml
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add helm/values.yaml
          git commit -m "Update image tag to ${{ env.IMAGE_TAG }}" || echo "No changes to commit"
          git push origin develop || echo "Push failed, maybe no changes"