name: Build & Deploy kbot

on:
  push:
    branches: [ main ]
    paths:
      - 'kbot/**'
      - '.github/workflows/ci-cd.yaml'

env:
  TARGETARCH: amd64
  TARGETOS: linux
  IMAGE_REGISTRY: docker.io
  IMAGE_REPOSITORY: andreysvirid/kbot

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run tests
        run: |
          go mod tidy
          go test ./...

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker image
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          IMAGE_TAG="v1.0.0-${SHORT_SHA}-${TARGETOS}-${TARGETARCH}"
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          docker buildx build \
            --platform ${{ env.TARGETOS }}/$TARGETARCH \
            -t ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:${IMAGE_TAG} \
            --push \
            kbot/

  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update Helm chart
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          VERSION="v1.0.0-${SHORT_SHA}"
          yq -i '.image.tag=strenv(VERSION) | .image.os=strenv(TARGETOS) | .image.arch=strenv(TARGETARCH)' charts/kbot/values.yaml

      - name: Commit Helm chart changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add charts/kbot/values.yaml
          git commit -m "Update image tag to $VERSION" || echo "No changes to commit"
          git push origin main
