name: CI/CD

on:
  push:
    branches: [ develop ]

env:
  TARGETARCH: amd64
  TARGETOS: linux
  IMAGE_REGISTRY: docker.io
  IMAGE_REPOSITORY: andreysvirid/kbot2   # твій образ у Docker Hub

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout develop
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2️⃣ Run tests
      - name: Run tests
        run: |
          go mod tidy
          go test ./...

      # 3️⃣ Login to Docker Hub
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4️⃣ Build & Push Docker image
      - name: Build & Push
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          IMAGE_TAG="v1.0.0-${SHORT_SHA}"
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          docker buildx build \
            --platform ${{ env.TARGETOS }}/${{ env.TARGETARCH }} \
            -t ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:${IMAGE_TAG} \
            --push \
            .

  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout develop
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2️⃣ Update Helm chart
      - name: Update Helm chart
        run: |
          VERSION="${{ env.IMAGE_TAG }}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          yq -i ".image.repository = \"${{ env.IMAGE_REPOSITORY }}\" | .image.tag = \"${VERSION}\"" helm/values.yaml

      # 3️⃣ Commit Helm chart changes
      - name: Commit Helm chart changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add helm/values.yaml
          git commit -m "ci: update image tag to ${{ env.VERSION }}" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB2_TOKEN }}@github.com/andreysvirid/gke-flux-infra.git
          git push origin develop